-- Seed data for pi_config_model_mesures
-- Generated from Google Sheets _MODELS export
-- Total rows: 417

INSERT INTO pi_config_model_mesures (model, tipus, mesura, sort_order)
VALUES
  ('Altes capacitats', 'Universal', 'Es clarifiquen els objectius de la tasca amb llenguatge planer i exemples.', 1),
  ('Dislèxia', 'Universal', 'Es clarifiquen els objectius de la tasca amb llenguatge planer i exemples.', 2),
  ('NEE', 'Universal', 'Es clarifiquen els objectius de la tasca amb llenguatge planer i exemples.', 3),
  ('Nouvingut', 'Universal', 'Es clarifiquen els objectius de la tasca amb llenguatge planer i exemples.', 4),
  ('TDAH', 'Universal', 'Es clarifiquen els objectius de la tasca amb llenguatge planer i exemples.', 5),
  ('TEA', 'Universal', 'Es clarifiquen els objectius de la tasca amb llenguatge planer i exemples.', 6),
  ('TEL/TDL', 'Universal', 'Es clarifiquen els objectius de la tasca amb llenguatge planer i exemples.', 7),
  ('Altes capacitats', 'Universal', 'Es combina explicació oral amb suport escrit i/o visual.', 8),
  ('Dislèxia', 'Universal', 'Es combina explicació oral amb suport escrit i/o visual.', 9),
  ('NEE', 'Universal', 'Es combina explicació oral amb suport escrit i/o visual.', 10),
  ('Nouvingut', 'Universal', 'Es combina explicació oral amb suport escrit i/o visual.', 11),
  ('TDAH', 'Universal', 'Es combina explicació oral amb suport escrit i/o visual.', 12),
  ('TEA', 'Universal', 'Es combina explicació oral amb suport escrit i/o visual.', 13),
  ('TEL/TDL', 'Universal', 'Es combina explicació oral amb suport escrit i/o visual.', 14),
  ('Altes capacitats', 'Universal', 'Es comprova la comprensió demanant que es reformuli la consigna.', 15),
  ('Dislèxia', 'Universal', 'Es comprova la comprensió demanant que es reformuli la consigna.', 16),
  ('NEE', 'Universal', 'Es comprova la comprensió demanant que es reformuli la consigna.', 17),
  ('Nouvingut', 'Universal', 'Es comprova la comprensió demanant que es reformuli la consigna.', 18),
  ('TDAH', 'Universal', 'Es comprova la comprensió demanant que es reformuli la consigna.', 19),
  ('TEA', 'Universal', 'Es comprova la comprensió demanant que es reformuli la consigna.', 20),
  ('TEL/TDL', 'Universal', 'Es comprova la comprensió demanant que es reformuli la consigna.', 21),
  ('Altes capacitats', 'Intensiu', 'Es concreta un pla de comunicació família-centre amb seguiment periòdic.', 22),
  ('Dislèxia', 'Intensiu', 'Es concreta un pla de comunicació família-centre amb seguiment periòdic.', 23),
  ('NEE', 'Intensiu', 'Es concreta un pla de comunicació família-centre amb seguiment periòdic.', 24),
  ('Nouvingut', 'Intensiu', 'Es concreta un pla de comunicació família-centre amb seguiment periòdic.', 25),
  ('TDAH', 'Intensiu', 'Es concreta un pla de comunicació família-centre amb seguiment periòdic.', 26),
  ('TEA', 'Intensiu', 'Es concreta un pla de comunicació família-centre amb seguiment periòdic.', 27),
  ('TEL/TDL', 'Intensiu', 'Es concreta un pla de comunicació família-centre amb seguiment periòdic.', 28),
  ('TDAH', 'Intensiu', 'Es concreta un pla de conducta coordinat amb família i equip docent, amb registre.', 29),
  ('Nouvingut', 'Intensiu', 'Es coordina un itinerari d''acollida lingüística amb objectius i evidències.', 30),
  ('Altes capacitats', 'Intensiu', 'Es coordina una intervenció amb EAP/CREDA o serveis especialitzats, si cal.', 31),
  ('Dislèxia', 'Intensiu', 'Es coordina una intervenció amb EAP/CREDA o serveis especialitzats, si cal.', 32),
  ('NEE', 'Intensiu', 'Es coordina una intervenció amb EAP/CREDA o serveis especialitzats, si cal.', 33),
  ('Nouvingut', 'Intensiu', 'Es coordina una intervenció amb EAP/CREDA o serveis especialitzats, si cal.', 34),
  ('TDAH', 'Intensiu', 'Es coordina una intervenció amb EAP/CREDA o serveis especialitzats, si cal.', 35),
  ('TEA', 'Intensiu', 'Es coordina una intervenció amb EAP/CREDA o serveis especialitzats, si cal.', 36),
  ('TEL/TDL', 'Intensiu', 'Es coordina una intervenció amb EAP/CREDA o serveis especialitzats, si cal.', 37),
  ('Altes capacitats', 'Addicional', 'Es coordinen criteris d''avaluació i adaptacions amb l''equip docent.', 38),
  ('Dislèxia', 'Addicional', 'Es coordinen criteris d''avaluació i adaptacions amb l''equip docent.', 39),
  ('NEE', 'Addicional', 'Es coordinen criteris d''avaluació i adaptacions amb l''equip docent.', 40),
  ('Nouvingut', 'Addicional', 'Es coordinen criteris d''avaluació i adaptacions amb l''equip docent.', 41),
  ('TDAH', 'Addicional', 'Es coordinen criteris d''avaluació i adaptacions amb l''equip docent.', 42),
  ('TEA', 'Addicional', 'Es coordinen criteris d''avaluació i adaptacions amb l''equip docent.', 43),
  ('TEL/TDL', 'Addicional', 'Es coordinen criteris d''avaluació i adaptacions amb l''equip docent.', 44),
  ('Altes capacitats', 'Intensiu', 'Es coordinen mesures d''enriquiment o flexibilització amb l''equip d''orientació, si s''escau.', 45),
  ('TEL/TDL', 'Intensiu', 'Es coordinen objectius de llenguatge amb la intervenció del/la logopeda o CREDA.', 46),
  ('Altes capacitats', 'Universal', 'Es cuida la ubicació a l''aula per facilitar atenció i interacció.', 47),
  ('Dislèxia', 'Universal', 'Es cuida la ubicació a l''aula per facilitar atenció i interacció.', 48),
  ('NEE', 'Universal', 'Es cuida la ubicació a l''aula per facilitar atenció i interacció.', 49),
  ('Nouvingut', 'Universal', 'Es cuida la ubicació a l''aula per facilitar atenció i interacció.', 50),
  ('TDAH', 'Universal', 'Es cuida la ubicació a l''aula per facilitar atenció i interacció.', 51),
  ('TEA', 'Universal', 'Es cuida la ubicació a l''aula per facilitar atenció i interacció.', 52),
  ('TEL/TDL', 'Universal', 'Es cuida la ubicació a l''aula per facilitar atenció i interacció.', 53),
  ('Altes capacitats', 'Intensiu', 'Es defineix un protocol d''avaluació adaptada amb criteris consensuats.', 54),
  ('Dislèxia', 'Intensiu', 'Es defineix un protocol d''avaluació adaptada amb criteris consensuats.', 55),
  ('NEE', 'Intensiu', 'Es defineix un protocol d''avaluació adaptada amb criteris consensuats.', 56),
  ('Nouvingut', 'Intensiu', 'Es defineix un protocol d''avaluació adaptada amb criteris consensuats.', 57),
  ('TDAH', 'Intensiu', 'Es defineix un protocol d''avaluació adaptada amb criteris consensuats.', 58),
  ('TEA', 'Intensiu', 'Es defineix un protocol d''avaluació adaptada amb criteris consensuats.', 59),
  ('TEL/TDL', 'Intensiu', 'Es defineix un protocol d''avaluació adaptada amb criteris consensuats.', 60),
  ('Dislèxia', 'Intensiu', 'Es defineixen adaptacions d''avaluació (lectura en veu alta, temps extra, format).', 61),
  ('Altes capacitats', 'Intensiu', 'Es defineixen adaptacions significatives del currículum quan s''escau.', 62),
  ('Dislèxia', 'Intensiu', 'Es defineixen adaptacions significatives del currículum quan s''escau.', 63),
  ('NEE', 'Intensiu', 'Es defineixen adaptacions significatives del currículum quan s''escau.', 64),
  ('Nouvingut', 'Intensiu', 'Es defineixen adaptacions significatives del currículum quan s''escau.', 65),
  ('TDAH', 'Intensiu', 'Es defineixen adaptacions significatives del currículum quan s''escau.', 66),
  ('TEA', 'Intensiu', 'Es defineixen adaptacions significatives del currículum quan s''escau.', 67),
  ('TEL/TDL', 'Intensiu', 'Es defineixen adaptacions significatives del currículum quan s''escau.', 68),
  ('NEE', 'Intensiu', 'Es defineixen adaptacions significatives i criteris d''avaluació específics.', 69),
  ('Altes capacitats', 'Universal', 'Es destaquen paraules clau i idees principals del material.', 70),
  ('Dislèxia', 'Universal', 'Es destaquen paraules clau i idees principals del material.', 71),
  ('NEE', 'Universal', 'Es destaquen paraules clau i idees principals del material.', 72),
  ('Nouvingut', 'Universal', 'Es destaquen paraules clau i idees principals del material.', 73),
  ('TDAH', 'Universal', 'Es destaquen paraules clau i idees principals del material.', 74),
  ('TEA', 'Universal', 'Es destaquen paraules clau i idees principals del material.', 75),
  ('TEL/TDL', 'Universal', 'Es destaquen paraules clau i idees principals del material.', 76),
  ('TDAH', 'Addicional', 'Es dissenya un pla d''organització amb materials mínims i revisió diària.', 77),
  ('Altes capacitats', 'Intensiu', 'Es dissenya un pla de treball individual amb objectius trimestrals mesurables.', 78),
  ('Dislèxia', 'Intensiu', 'Es dissenya un pla de treball individual amb objectius trimestrals mesurables.', 79),
  ('NEE', 'Intensiu', 'Es dissenya un pla de treball individual amb objectius trimestrals mesurables.', 80),
  ('Nouvingut', 'Intensiu', 'Es dissenya un pla de treball individual amb objectius trimestrals mesurables.', 81),
  ('TDAH', 'Intensiu', 'Es dissenya un pla de treball individual amb objectius trimestrals mesurables.', 82),
  ('TEA', 'Intensiu', 'Es dissenya un pla de treball individual amb objectius trimestrals mesurables.', 83),
  ('TEL/TDL', 'Intensiu', 'Es dissenya un pla de treball individual amb objectius trimestrals mesurables.', 84),
  ('TEA', 'Intensiu', 'Es dissenya un pla individual de regulació emocional amb estratègies i adults referents.', 85),
  ('Altes capacitats', 'Addicional', 'Es dissenyen tasques amb opcions de dificultat (bàsica, estàndard, avançada).', 86),
  ('Dislèxia', 'Addicional', 'Es dissenyen tasques amb opcions de dificultat (bàsica, estàndard, avançada).', 87),
  ('NEE', 'Addicional', 'Es dissenyen tasques amb opcions de dificultat (bàsica, estàndard, avançada).', 88),
  ('Nouvingut', 'Addicional', 'Es dissenyen tasques amb opcions de dificultat (bàsica, estàndard, avançada).', 89),
  ('TDAH', 'Addicional', 'Es dissenyen tasques amb opcions de dificultat (bàsica, estàndard, avançada).', 90),
  ('TEA', 'Addicional', 'Es dissenyen tasques amb opcions de dificultat (bàsica, estàndard, avançada).', 91),
  ('TEL/TDL', 'Addicional', 'Es dissenyen tasques amb opcions de dificultat (bàsica, estàndard, avançada).', 92),
  ('Altes capacitats', 'Universal', 'Es divideix la feina en passos petits i s''indica l''ordre de treball.', 93),
  ('Dislèxia', 'Universal', 'Es divideix la feina en passos petits i s''indica l''ordre de treball.', 94),
  ('NEE', 'Universal', 'Es divideix la feina en passos petits i s''indica l''ordre de treball.', 95),
  ('Nouvingut', 'Universal', 'Es divideix la feina en passos petits i s''indica l''ordre de treball.', 96),
  ('TDAH', 'Universal', 'Es divideix la feina en passos petits i s''indica l''ordre de treball.', 97),
  ('TEA', 'Universal', 'Es divideix la feina en passos petits i s''indica l''ordre de treball.', 98),
  ('TEL/TDL', 'Universal', 'Es divideix la feina en passos petits i s''indica l''ordre de treball.', 99),
  ('Altes capacitats', 'Addicional', 'Es dona més temps en tasques i proves sense penalització per ritme.', 100),
  ('Dislèxia', 'Addicional', 'Es dona més temps en tasques i proves sense penalització per ritme.', 101),
  ('NEE', 'Addicional', 'Es dona més temps en tasques i proves sense penalització per ritme.', 102),
  ('Nouvingut', 'Addicional', 'Es dona més temps en tasques i proves sense penalització per ritme.', 103),
  ('TDAH', 'Addicional', 'Es dona més temps en tasques i proves sense penalització per ritme.', 104),
  ('TEA', 'Addicional', 'Es dona més temps en tasques i proves sense penalització per ritme.', 105),
  ('TEL/TDL', 'Addicional', 'Es dona més temps en tasques i proves sense penalització per ritme.', 106),
  ('Altes capacitats', 'Addicional', 'Es dona suport en petit grup per practicar continguts clau amb guia docent.', 107),
  ('Dislèxia', 'Addicional', 'Es dona suport en petit grup per practicar continguts clau amb guia docent.', 108),
  ('NEE', 'Addicional', 'Es dona suport en petit grup per practicar continguts clau amb guia docent.', 109),
  ('Nouvingut', 'Addicional', 'Es dona suport en petit grup per practicar continguts clau amb guia docent.', 110),
  ('TDAH', 'Addicional', 'Es dona suport en petit grup per practicar continguts clau amb guia docent.', 111),
  ('TEA', 'Addicional', 'Es dona suport en petit grup per practicar continguts clau amb guia docent.', 112),
  ('TEL/TDL', 'Addicional', 'Es dona suport en petit grup per practicar continguts clau amb guia docent.', 113),
  ('Altes capacitats', 'Universal', 'Es dona temps de planificació abans de respondre o escriure.', 114),
  ('Dislèxia', 'Universal', 'Es dona temps de planificació abans de respondre o escriure.', 115),
  ('NEE', 'Universal', 'Es dona temps de planificació abans de respondre o escriure.', 116),
  ('Nouvingut', 'Universal', 'Es dona temps de planificació abans de respondre o escriure.', 117),
  ('TDAH', 'Universal', 'Es dona temps de planificació abans de respondre o escriure.', 118),
  ('TEA', 'Universal', 'Es dona temps de planificació abans de respondre o escriure.', 119),
  ('TEL/TDL', 'Universal', 'Es dona temps de planificació abans de respondre o escriure.', 120),
  ('TEL/TDL', 'Addicional', 'Es dona temps extra per planificar i expressar-se oralment sense interrupcions.', 121),
  ('Altes capacitats', 'Universal', 'Es dona un recordatori visual del temps (temporitzador o pauta).', 122),
  ('Dislèxia', 'Universal', 'Es dona un recordatori visual del temps (temporitzador o pauta).', 123),
  ('NEE', 'Universal', 'Es dona un recordatori visual del temps (temporitzador o pauta).', 124),
  ('Nouvingut', 'Universal', 'Es dona un recordatori visual del temps (temporitzador o pauta).', 125),
  ('TDAH', 'Universal', 'Es dona un recordatori visual del temps (temporitzador o pauta).', 126),
  ('TEA', 'Universal', 'Es dona un recordatori visual del temps (temporitzador o pauta).', 127),
  ('TEL/TDL', 'Universal', 'Es dona un recordatori visual del temps (temporitzador o pauta).', 128),
  ('TDAH', 'Universal', 'Es dona un senyal acordat per redirigir l''atenció de manera discreta.', 129),
  ('Altes capacitats', 'Universal', 'Es donen instruccions curtes i es deixen visibles (pissarra o full).', 130),
  ('Dislèxia', 'Universal', 'Es donen instruccions curtes i es deixen visibles (pissarra o full).', 131),
  ('NEE', 'Universal', 'Es donen instruccions curtes i es deixen visibles (pissarra o full).', 132),
  ('Nouvingut', 'Universal', 'Es donen instruccions curtes i es deixen visibles (pissarra o full).', 133),
  ('TDAH', 'Universal', 'Es donen instruccions curtes i es deixen visibles (pissarra o full).', 134),
  ('TEA', 'Universal', 'Es donen instruccions curtes i es deixen visibles (pissarra o full).', 135),
  ('TEL/TDL', 'Universal', 'Es donen instruccions curtes i es deixen visibles (pissarra o full).', 136),
  ('TEA', 'Universal', 'Es donen opcions de resposta i de participació per reduir ansietat.', 137),
  ('Altes capacitats', 'Intensiu', 'Es estableix un pla de conducta amb objectius, reforços i seguiment.', 138),
  ('Dislèxia', 'Intensiu', 'Es estableix un pla de conducta amb objectius, reforços i seguiment.', 139),
  ('NEE', 'Intensiu', 'Es estableix un pla de conducta amb objectius, reforços i seguiment.', 140),
  ('Nouvingut', 'Intensiu', 'Es estableix un pla de conducta amb objectius, reforços i seguiment.', 141),
  ('TDAH', 'Intensiu', 'Es estableix un pla de conducta amb objectius, reforços i seguiment.', 142),
  ('TEA', 'Intensiu', 'Es estableix un pla de conducta amb objectius, reforços i seguiment.', 143),
  ('TEL/TDL', 'Intensiu', 'Es estableix un pla de conducta amb objectius, reforços i seguiment.', 144),
  ('Altes capacitats', 'Addicional', 'Es fa coavaluació guiada amb rúbriques simples per millorar el producte.', 145),
  ('Dislèxia', 'Addicional', 'Es fa coavaluació guiada amb rúbriques simples per millorar el producte.', 146),
  ('NEE', 'Addicional', 'Es fa coavaluació guiada amb rúbriques simples per millorar el producte.', 147),
  ('Nouvingut', 'Addicional', 'Es fa coavaluació guiada amb rúbriques simples per millorar el producte.', 148),
  ('TDAH', 'Addicional', 'Es fa coavaluació guiada amb rúbriques simples per millorar el producte.', 149),
  ('TEA', 'Addicional', 'Es fa coavaluació guiada amb rúbriques simples per millorar el producte.', 150),
  ('TEL/TDL', 'Addicional', 'Es fa coavaluació guiada amb rúbriques simples per millorar el producte.', 151),
  ('Nouvingut', 'Universal', 'Es fa ús de suport visual i gestual per assegurar la comprensió del vocabulari.', 152),
  ('Altes capacitats', 'Addicional', 'Es facilita lectura en veu alta o audiotext quan la comprensió ho requereix.', 153),
  ('Dislèxia', 'Addicional', 'Es facilita lectura en veu alta o audiotext quan la comprensió ho requereix.', 154),
  ('NEE', 'Addicional', 'Es facilita lectura en veu alta o audiotext quan la comprensió ho requereix.', 155),
  ('Nouvingut', 'Addicional', 'Es facilita lectura en veu alta o audiotext quan la comprensió ho requereix.', 156),
  ('TDAH', 'Addicional', 'Es facilita lectura en veu alta o audiotext quan la comprensió ho requereix.', 157),
  ('TEA', 'Addicional', 'Es facilita lectura en veu alta o audiotext quan la comprensió ho requereix.', 158),
  ('TEL/TDL', 'Addicional', 'Es facilita lectura en veu alta o audiotext quan la comprensió ho requereix.', 159),
  ('Dislèxia', 'Universal', 'Es facilita tipografia clara, espaiat adequat i formats accessibles en materials.', 160),
  ('Nouvingut', 'Addicional', 'Es facilita un banc de frases model i vocabulari funcional per a la matèria.', 161),
  ('Altes capacitats', 'Addicional', 'Es facilita un glossari personalitzat de la unitat amb definicions simples.', 162),
  ('Dislèxia', 'Addicional', 'Es facilita un glossari personalitzat de la unitat amb definicions simples.', 163),
  ('NEE', 'Addicional', 'Es facilita un glossari personalitzat de la unitat amb definicions simples.', 164),
  ('Nouvingut', 'Addicional', 'Es facilita un glossari personalitzat de la unitat amb definicions simples.', 165),
  ('TDAH', 'Addicional', 'Es facilita un glossari personalitzat de la unitat amb definicions simples.', 166),
  ('TEA', 'Addicional', 'Es facilita un glossari personalitzat de la unitat amb definicions simples.', 167),
  ('TEL/TDL', 'Addicional', 'Es facilita un glossari personalitzat de la unitat amb definicions simples.', 168),
  ('Altes capacitats', 'Addicional', 'Es facilita un itinerari d''aprofundiment amb fonts i producte final.', 169),
  ('Altes capacitats', 'Addicional', 'Es facilita un resum de la sessió i una pauta d''estudi per a casa.', 170),
  ('Dislèxia', 'Addicional', 'Es facilita un resum de la sessió i una pauta d''estudi per a casa.', 171),
  ('NEE', 'Addicional', 'Es facilita un resum de la sessió i una pauta d''estudi per a casa.', 172),
  ('Nouvingut', 'Addicional', 'Es facilita un resum de la sessió i una pauta d''estudi per a casa.', 173),
  ('TDAH', 'Addicional', 'Es facilita un resum de la sessió i una pauta d''estudi per a casa.', 174),
  ('TEA', 'Addicional', 'Es facilita un resum de la sessió i una pauta d''estudi per a casa.', 175),
  ('TEL/TDL', 'Addicional', 'Es facilita un resum de la sessió i una pauta d''estudi per a casa.', 176),
  ('TEL/TDL', 'Addicional', 'Es facilita una pauta de frases i connectors per estructurar les respostes.', 177),
  ('Altes capacitats', 'Universal', 'Es facilita vocabulari previ i es treballen conceptes abans de la tasca.', 178),
  ('Dislèxia', 'Universal', 'Es facilita vocabulari previ i es treballen conceptes abans de la tasca.', 179),
  ('NEE', 'Universal', 'Es facilita vocabulari previ i es treballen conceptes abans de la tasca.', 180),
  ('Nouvingut', 'Universal', 'Es facilita vocabulari previ i es treballen conceptes abans de la tasca.', 181),
  ('TDAH', 'Universal', 'Es facilita vocabulari previ i es treballen conceptes abans de la tasca.', 182),
  ('TEA', 'Universal', 'Es facilita vocabulari previ i es treballen conceptes abans de la tasca.', 183),
  ('TEL/TDL', 'Universal', 'Es facilita vocabulari previ i es treballen conceptes abans de la tasca.', 184),
  ('Altes capacitats', 'Universal', 'Es faciliten organitzadors gràfics (esquema, taula, mapa conceptual).', 185),
  ('Dislèxia', 'Universal', 'Es faciliten organitzadors gràfics (esquema, taula, mapa conceptual).', 186),
  ('NEE', 'Universal', 'Es faciliten organitzadors gràfics (esquema, taula, mapa conceptual).', 187),
  ('Nouvingut', 'Universal', 'Es faciliten organitzadors gràfics (esquema, taula, mapa conceptual).', 188),
  ('TDAH', 'Universal', 'Es faciliten organitzadors gràfics (esquema, taula, mapa conceptual).', 189),
  ('TEA', 'Universal', 'Es faciliten organitzadors gràfics (esquema, taula, mapa conceptual).', 190),
  ('TEL/TDL', 'Universal', 'Es faciliten organitzadors gràfics (esquema, taula, mapa conceptual).', 191),
  ('TEA', 'Universal', 'Es fan anticipacions visuals de la sessió (agenda visual) i de les transicions.', 192),
  ('Altes capacitats', 'Universal', 'Es fomenta la participació amb preguntes guiades i torns clars.', 193),
  ('Dislèxia', 'Universal', 'Es fomenta la participació amb preguntes guiades i torns clars.', 194),
  ('NEE', 'Universal', 'Es fomenta la participació amb preguntes guiades i torns clars.', 195),
  ('Nouvingut', 'Universal', 'Es fomenta la participació amb preguntes guiades i torns clars.', 196),
  ('TDAH', 'Universal', 'Es fomenta la participació amb preguntes guiades i torns clars.', 197),
  ('TEA', 'Universal', 'Es fomenta la participació amb preguntes guiades i torns clars.', 198),
  ('TEL/TDL', 'Universal', 'Es fomenta la participació amb preguntes guiades i torns clars.', 199),
  ('Dislèxia', 'Addicional', 'Es fragmenten textos llargs i s''ofereix suport de lectura guiada.', 200),
  ('Altes capacitats', 'Universal', 'Es manté un to de classe respectuós i previsible, amb normes explícites.', 201),
  ('Dislèxia', 'Universal', 'Es manté un to de classe respectuós i previsible, amb normes explícites.', 202),
  ('NEE', 'Universal', 'Es manté un to de classe respectuós i previsible, amb normes explícites.', 203),
  ('Nouvingut', 'Universal', 'Es manté un to de classe respectuós i previsible, amb normes explícites.', 204),
  ('TDAH', 'Universal', 'Es manté un to de classe respectuós i previsible, amb normes explícites.', 205),
  ('TEA', 'Universal', 'Es manté un to de classe respectuós i previsible, amb normes explícites.', 206),
  ('TEL/TDL', 'Universal', 'Es manté un to de classe respectuós i previsible, amb normes explícites.', 207),
  ('TEA', 'Intensiu', 'Es pacta un protocol davant crisis amb senyals, passos i responsabilitats.', 208),
  ('Altes capacitats', 'Addicional', 'Es pacten objectius setmanals i es revisen amb retorn concret.', 209),
  ('Dislèxia', 'Addicional', 'Es pacten objectius setmanals i es revisen amb retorn concret.', 210),
  ('NEE', 'Addicional', 'Es pacten objectius setmanals i es revisen amb retorn concret.', 211),
  ('Nouvingut', 'Addicional', 'Es pacten objectius setmanals i es revisen amb retorn concret.', 212),
  ('TDAH', 'Addicional', 'Es pacten objectius setmanals i es revisen amb retorn concret.', 213),
  ('TEA', 'Addicional', 'Es pacten objectius setmanals i es revisen amb retorn concret.', 214),
  ('TEL/TDL', 'Addicional', 'Es pacten objectius setmanals i es revisen amb retorn concret.', 215),
  ('Altes capacitats', 'Addicional', 'Es permet compactació de continguts i ampliació en projectes d''interès.', 216),
  ('Altes capacitats', 'Universal', 'Es permet demostrar l''aprenentatge amb formats diversos quan és possible.', 217),
  ('Dislèxia', 'Universal', 'Es permet demostrar l''aprenentatge amb formats diversos quan és possible.', 218),
  ('NEE', 'Universal', 'Es permet demostrar l''aprenentatge amb formats diversos quan és possible.', 219),
  ('Nouvingut', 'Universal', 'Es permet demostrar l''aprenentatge amb formats diversos quan és possible.', 220),
  ('TDAH', 'Universal', 'Es permet demostrar l''aprenentatge amb formats diversos quan és possible.', 221),
  ('TEA', 'Universal', 'Es permet demostrar l''aprenentatge amb formats diversos quan és possible.', 222),
  ('TEL/TDL', 'Universal', 'Es permet demostrar l''aprenentatge amb formats diversos quan és possible.', 223),
  ('Dislèxia', 'Addicional', 'Es permet l''ús d''audiollibres, lector de pantalla o dictat per veu quan cal.', 224),
  ('Altes capacitats', 'Addicional', 'Es permet l''ús de calculadora o taules de suport quan és pedagògic.', 225),
  ('Dislèxia', 'Addicional', 'Es permet l''ús de calculadora o taules de suport quan és pedagògic.', 226),
  ('NEE', 'Addicional', 'Es permet l''ús de calculadora o taules de suport quan és pedagògic.', 227),
  ('Nouvingut', 'Addicional', 'Es permet l''ús de calculadora o taules de suport quan és pedagògic.', 228),
  ('TDAH', 'Addicional', 'Es permet l''ús de calculadora o taules de suport quan és pedagògic.', 229),
  ('TEA', 'Addicional', 'Es permet l''ús de calculadora o taules de suport quan és pedagògic.', 230),
  ('TEL/TDL', 'Addicional', 'Es permet l''ús de calculadora o taules de suport quan és pedagògic.', 231),
  ('Altes capacitats', 'Universal', 'Es permet l''ús de suport visual (pictogrames, icones, codis de colors).', 232),
  ('Dislèxia', 'Universal', 'Es permet l''ús de suport visual (pictogrames, icones, codis de colors).', 233),
  ('NEE', 'Universal', 'Es permet l''ús de suport visual (pictogrames, icones, codis de colors).', 234),
  ('Nouvingut', 'Universal', 'Es permet l''ús de suport visual (pictogrames, icones, codis de colors).', 235),
  ('TDAH', 'Universal', 'Es permet l''ús de suport visual (pictogrames, icones, codis de colors).', 236),
  ('TEA', 'Universal', 'Es permet l''ús de suport visual (pictogrames, icones, codis de colors).', 237),
  ('TEL/TDL', 'Universal', 'Es permet l''ús de suport visual (pictogrames, icones, codis de colors).', 238),
  ('TDAH', 'Addicional', 'Es permet moviment funcional (encàrrecs, estacions) sense trencar la dinàmica.', 239),
  ('Altes capacitats', 'Addicional', 'Es permet respondre oralment o amb dictat al dispositiu quan cal.', 240),
  ('Dislèxia', 'Addicional', 'Es permet respondre oralment o amb dictat al dispositiu quan cal.', 241),
  ('NEE', 'Addicional', 'Es permet respondre oralment o amb dictat al dispositiu quan cal.', 242),
  ('Nouvingut', 'Addicional', 'Es permet respondre oralment o amb dictat al dispositiu quan cal.', 243),
  ('TDAH', 'Addicional', 'Es permet respondre oralment o amb dictat al dispositiu quan cal.', 244),
  ('TEA', 'Addicional', 'Es permet respondre oralment o amb dictat al dispositiu quan cal.', 245),
  ('TEL/TDL', 'Addicional', 'Es permet respondre oralment o amb dictat al dispositiu quan cal.', 246),
  ('Nouvingut', 'Addicional', 'Es permet respondre parcialment en llengua d''origen o amb suport visual quan cal.', 247),
  ('NEE', 'Intensiu', 'Es planifica suport d''educació especial o vetllador/a segons necessitats.', 248),
  ('TEA', 'Addicional', 'Es planifica un espai o temps de regulació amb pautes acordades.', 249),
  ('Altes capacitats', 'Addicional', 'Es planifica una adaptació de proves (format, longitud, suport visual).', 250),
  ('Dislèxia', 'Addicional', 'Es planifica una adaptació de proves (format, longitud, suport visual).', 251),
  ('NEE', 'Addicional', 'Es planifica una adaptació de proves (format, longitud, suport visual).', 252),
  ('Nouvingut', 'Addicional', 'Es planifica una adaptació de proves (format, longitud, suport visual).', 253),
  ('TDAH', 'Addicional', 'Es planifica una adaptació de proves (format, longitud, suport visual).', 254),
  ('TEA', 'Addicional', 'Es planifica una adaptació de proves (format, longitud, suport visual).', 255),
  ('TEL/TDL', 'Addicional', 'Es planifica una adaptació de proves (format, longitud, suport visual).', 256),
  ('TEL/TDL', 'Intensiu', 'Es planifica una intervenció específica en comprensió i expressió amb materials graduats.', 257),
  ('Altes capacitats', 'Universal', 'Es planifica una tutoria breu periòdica per fer seguiment de l''alumne/a.', 258),
  ('Dislèxia', 'Universal', 'Es planifica una tutoria breu periòdica per fer seguiment de l''alumne/a.', 259),
  ('NEE', 'Universal', 'Es planifica una tutoria breu periòdica per fer seguiment de l''alumne/a.', 260),
  ('Nouvingut', 'Universal', 'Es planifica una tutoria breu periòdica per fer seguiment de l''alumne/a.', 261),
  ('TDAH', 'Universal', 'Es planifica una tutoria breu periòdica per fer seguiment de l''alumne/a.', 262),
  ('TEA', 'Universal', 'Es planifica una tutoria breu periòdica per fer seguiment de l''alumne/a.', 263),
  ('TEL/TDL', 'Universal', 'Es planifica una tutoria breu periòdica per fer seguiment de l''alumne/a.', 264),
  ('TDAH', 'Universal', 'Es planifiquen tasques curtes amb objectius immediats i reforç positiu.', 265),
  ('NEE', 'Addicional', 'Es prepara material manipulatiu o adaptat per accedir als conceptes clau.', 266),
  ('Altes capacitats', 'Addicional', 'Es prepara un dossier de reforç amb activitats graduades i autocorrectives.', 267),
  ('Dislèxia', 'Addicional', 'Es prepara un dossier de reforç amb activitats graduades i autocorrectives.', 268),
  ('NEE', 'Addicional', 'Es prepara un dossier de reforç amb activitats graduades i autocorrectives.', 269),
  ('Nouvingut', 'Addicional', 'Es prepara un dossier de reforç amb activitats graduades i autocorrectives.', 270),
  ('TDAH', 'Addicional', 'Es prepara un dossier de reforç amb activitats graduades i autocorrectives.', 271),
  ('TEA', 'Addicional', 'Es prepara un dossier de reforç amb activitats graduades i autocorrectives.', 272),
  ('TEL/TDL', 'Addicional', 'Es prepara un dossier de reforç amb activitats graduades i autocorrectives.', 273),
  ('Altes capacitats', 'Universal', 'Es preveuen models o exemples resolts abans de començar.', 274),
  ('Dislèxia', 'Universal', 'Es preveuen models o exemples resolts abans de començar.', 275),
  ('NEE', 'Universal', 'Es preveuen models o exemples resolts abans de començar.', 276),
  ('Nouvingut', 'Universal', 'Es preveuen models o exemples resolts abans de començar.', 277),
  ('TDAH', 'Universal', 'Es preveuen models o exemples resolts abans de començar.', 278),
  ('TEA', 'Universal', 'Es preveuen models o exemples resolts abans de començar.', 279),
  ('TEL/TDL', 'Universal', 'Es preveuen models o exemples resolts abans de començar.', 280),
  ('Dislèxia', 'Universal', 'Es prioritza la comprensió del text i no es penalitza l''ortografia quan no és l''objectiu.', 281),
  ('Altes capacitats', 'Universal', 'Es prioritzen criteris d''avaluació essencials i es comunica què és clau.', 282),
  ('Dislèxia', 'Universal', 'Es prioritzen criteris d''avaluació essencials i es comunica què és clau.', 283),
  ('NEE', 'Universal', 'Es prioritzen criteris d''avaluació essencials i es comunica què és clau.', 284),
  ('Nouvingut', 'Universal', 'Es prioritzen criteris d''avaluació essencials i es comunica què és clau.', 285),
  ('TDAH', 'Universal', 'Es prioritzen criteris d''avaluació essencials i es comunica què és clau.', 286),
  ('TEA', 'Universal', 'Es prioritzen criteris d''avaluació essencials i es comunica què és clau.', 287),
  ('TEL/TDL', 'Universal', 'Es prioritzen criteris d''avaluació essencials i es comunica què és clau.', 288),
  ('Altes capacitats', 'Intensiu', 'Es prioritzen objectius funcionals i competencials per a l''autonomia.', 289),
  ('Dislèxia', 'Intensiu', 'Es prioritzen objectius funcionals i competencials per a l''autonomia.', 290),
  ('NEE', 'Intensiu', 'Es prioritzen objectius funcionals i competencials per a l''autonomia.', 291),
  ('Nouvingut', 'Intensiu', 'Es prioritzen objectius funcionals i competencials per a l''autonomia.', 292),
  ('TDAH', 'Intensiu', 'Es prioritzen objectius funcionals i competencials per a l''autonomia.', 293),
  ('TEA', 'Intensiu', 'Es prioritzen objectius funcionals i competencials per a l''autonomia.', 294),
  ('TEL/TDL', 'Intensiu', 'Es prioritzen objectius funcionals i competencials per a l''autonomia.', 295),
  ('Altes capacitats', 'Addicional', 'Es programa un suport puntual d''un adult a l''aula en moments clau.', 296),
  ('Dislèxia', 'Addicional', 'Es programa un suport puntual d''un adult a l''aula en moments clau.', 297),
  ('NEE', 'Addicional', 'Es programa un suport puntual d''un adult a l''aula en moments clau.', 298),
  ('Nouvingut', 'Addicional', 'Es programa un suport puntual d''un adult a l''aula en moments clau.', 299),
  ('TDAH', 'Addicional', 'Es programa un suport puntual d''un adult a l''aula en moments clau.', 300),
  ('TEA', 'Addicional', 'Es programa un suport puntual d''un adult a l''aula en moments clau.', 301),
  ('TEL/TDL', 'Addicional', 'Es programa un suport puntual d''un adult a l''aula en moments clau.', 302),
  ('Altes capacitats', 'Universal', 'Es programen pauses breus i estructurades durant la feina.', 303),
  ('Dislèxia', 'Universal', 'Es programen pauses breus i estructurades durant la feina.', 304),
  ('NEE', 'Universal', 'Es programen pauses breus i estructurades durant la feina.', 305),
  ('Nouvingut', 'Universal', 'Es programen pauses breus i estructurades durant la feina.', 306),
  ('TDAH', 'Universal', 'Es programen pauses breus i estructurades durant la feina.', 307),
  ('TEA', 'Universal', 'Es programen pauses breus i estructurades durant la feina.', 308),
  ('TEL/TDL', 'Universal', 'Es programen pauses breus i estructurades durant la feina.', 309),
  ('Altes capacitats', 'Addicional', 'Es programen recordatoris i ajudes per a l''organització (agenda, checklists).', 310),
  ('Dislèxia', 'Addicional', 'Es programen recordatoris i ajudes per a l''organització (agenda, checklists).', 311),
  ('NEE', 'Addicional', 'Es programen recordatoris i ajudes per a l''organització (agenda, checklists).', 312),
  ('Nouvingut', 'Addicional', 'Es programen recordatoris i ajudes per a l''organització (agenda, checklists).', 313),
  ('TDAH', 'Addicional', 'Es programen recordatoris i ajudes per a l''organització (agenda, checklists).', 314),
  ('TEA', 'Addicional', 'Es programen recordatoris i ajudes per a l''organització (agenda, checklists).', 315),
  ('TEL/TDL', 'Addicional', 'Es programen recordatoris i ajudes per a l''organització (agenda, checklists).', 316),
  ('Altes capacitats', 'Intensiu', 'Es programen sessions de suport individual setmanals amb registre de progrés.', 317),
  ('Dislèxia', 'Intensiu', 'Es programen sessions de suport individual setmanals amb registre de progrés.', 318),
  ('NEE', 'Intensiu', 'Es programen sessions de suport individual setmanals amb registre de progrés.', 319),
  ('Nouvingut', 'Intensiu', 'Es programen sessions de suport individual setmanals amb registre de progrés.', 320),
  ('TDAH', 'Intensiu', 'Es programen sessions de suport individual setmanals amb registre de progrés.', 321),
  ('TEA', 'Intensiu', 'Es programen sessions de suport individual setmanals amb registre de progrés.', 322),
  ('TEL/TDL', 'Intensiu', 'Es programen sessions de suport individual setmanals amb registre de progrés.', 323),
  ('Altes capacitats', 'Universal', 'Es promou el treball cooperatiu amb rols definits i suport del docent.', 324),
  ('Dislèxia', 'Universal', 'Es promou el treball cooperatiu amb rols definits i suport del docent.', 325),
  ('NEE', 'Universal', 'Es promou el treball cooperatiu amb rols definits i suport del docent.', 326),
  ('Nouvingut', 'Universal', 'Es promou el treball cooperatiu amb rols definits i suport del docent.', 327),
  ('TDAH', 'Universal', 'Es promou el treball cooperatiu amb rols definits i suport del docent.', 328),
  ('TEA', 'Universal', 'Es promou el treball cooperatiu amb rols definits i suport del docent.', 329),
  ('TEL/TDL', 'Universal', 'Es promou el treball cooperatiu amb rols definits i suport del docent.', 330),
  ('Altes capacitats', 'Universal', 'Es proporciona retroacció immediata, concreta i orientada a la millora.', 331),
  ('Dislèxia', 'Universal', 'Es proporciona retroacció immediata, concreta i orientada a la millora.', 332),
  ('NEE', 'Universal', 'Es proporciona retroacció immediata, concreta i orientada a la millora.', 333),
  ('Nouvingut', 'Universal', 'Es proporciona retroacció immediata, concreta i orientada a la millora.', 334),
  ('TDAH', 'Universal', 'Es proporciona retroacció immediata, concreta i orientada a la millora.', 335),
  ('TEA', 'Universal', 'Es proporciona retroacció immediata, concreta i orientada a la millora.', 336),
  ('TEL/TDL', 'Universal', 'Es proporciona retroacció immediata, concreta i orientada a la millora.', 337),
  ('Altes capacitats', 'Addicional', 'Es proporciona suport per iniciar la tasca (primer pas fet conjuntament).', 338),
  ('Dislèxia', 'Addicional', 'Es proporciona suport per iniciar la tasca (primer pas fet conjuntament).', 339),
  ('NEE', 'Addicional', 'Es proporciona suport per iniciar la tasca (primer pas fet conjuntament).', 340),
  ('Nouvingut', 'Addicional', 'Es proporciona suport per iniciar la tasca (primer pas fet conjuntament).', 341),
  ('TDAH', 'Addicional', 'Es proporciona suport per iniciar la tasca (primer pas fet conjuntament).', 342),
  ('TEA', 'Addicional', 'Es proporciona suport per iniciar la tasca (primer pas fet conjuntament).', 343),
  ('TEL/TDL', 'Addicional', 'Es proporciona suport per iniciar la tasca (primer pas fet conjuntament).', 344),
  ('Altes capacitats', 'Addicional', 'Es proporciona una pauta de correcció amb exemples d''errors freqüents.', 345),
  ('Dislèxia', 'Addicional', 'Es proporciona una pauta de correcció amb exemples d''errors freqüents.', 346),
  ('NEE', 'Addicional', 'Es proporciona una pauta de correcció amb exemples d''errors freqüents.', 347),
  ('Nouvingut', 'Addicional', 'Es proporciona una pauta de correcció amb exemples d''errors freqüents.', 348),
  ('TDAH', 'Addicional', 'Es proporciona una pauta de correcció amb exemples d''errors freqüents.', 349),
  ('TEA', 'Addicional', 'Es proporciona una pauta de correcció amb exemples d''errors freqüents.', 350),
  ('TEL/TDL', 'Addicional', 'Es proporciona una pauta de correcció amb exemples d''errors freqüents.', 351),
  ('Altes capacitats', 'Addicional', 'Es proposen activitats d''ampliació guiada quan s''assoleixen els mínims.', 352),
  ('Dislèxia', 'Addicional', 'Es proposen activitats d''ampliació guiada quan s''assoleixen els mínims.', 353),
  ('NEE', 'Addicional', 'Es proposen activitats d''ampliació guiada quan s''assoleixen els mínims.', 354),
  ('Nouvingut', 'Addicional', 'Es proposen activitats d''ampliació guiada quan s''assoleixen els mínims.', 355),
  ('TDAH', 'Addicional', 'Es proposen activitats d''ampliació guiada quan s''assoleixen els mínims.', 356),
  ('TEA', 'Addicional', 'Es proposen activitats d''ampliació guiada quan s''assoleixen els mínims.', 357),
  ('TEL/TDL', 'Addicional', 'Es proposen activitats d''ampliació guiada quan s''assoleixen els mínims.', 358),
  ('Altes capacitats', 'Universal', 'Es proposen reptes oberts i tasques d''investigació amb criteris clars.', 359),
  ('Altes capacitats', 'Intensiu', 'Es realitza una intervenció específica i sistemàtica en habilitats bàsiques.', 360),
  ('Dislèxia', 'Intensiu', 'Es realitza una intervenció específica i sistemàtica en habilitats bàsiques.', 361),
  ('NEE', 'Intensiu', 'Es realitza una intervenció específica i sistemàtica en habilitats bàsiques.', 362),
  ('Nouvingut', 'Intensiu', 'Es realitza una intervenció específica i sistemàtica en habilitats bàsiques.', 363),
  ('TDAH', 'Intensiu', 'Es realitza una intervenció específica i sistemàtica en habilitats bàsiques.', 364),
  ('TEA', 'Intensiu', 'Es realitza una intervenció específica i sistemàtica en habilitats bàsiques.', 365),
  ('TEL/TDL', 'Intensiu', 'Es realitza una intervenció específica i sistemàtica en habilitats bàsiques.', 366),
  ('Altes capacitats', 'Addicional', 'Es redueix el volum d''exercicis mantenint els objectius essencials.', 367),
  ('Dislèxia', 'Addicional', 'Es redueix el volum d''exercicis mantenint els objectius essencials.', 368),
  ('NEE', 'Addicional', 'Es redueix el volum d''exercicis mantenint els objectius essencials.', 369),
  ('Nouvingut', 'Addicional', 'Es redueix el volum d''exercicis mantenint els objectius essencials.', 370),
  ('TDAH', 'Addicional', 'Es redueix el volum d''exercicis mantenint els objectius essencials.', 371),
  ('TEA', 'Addicional', 'Es redueix el volum d''exercicis mantenint els objectius essencials.', 372),
  ('TEL/TDL', 'Addicional', 'Es redueix el volum d''exercicis mantenint els objectius essencials.', 373),
  ('Altes capacitats', 'Universal', 'Es redueix la càrrega de còpia i es faciliten plantilles o fitxes.', 374),
  ('Dislèxia', 'Universal', 'Es redueix la càrrega de còpia i es faciliten plantilles o fitxes.', 375),
  ('NEE', 'Universal', 'Es redueix la càrrega de còpia i es faciliten plantilles o fitxes.', 376),
  ('Nouvingut', 'Universal', 'Es redueix la càrrega de còpia i es faciliten plantilles o fitxes.', 377),
  ('TDAH', 'Universal', 'Es redueix la càrrega de còpia i es faciliten plantilles o fitxes.', 378),
  ('TEA', 'Universal', 'Es redueix la càrrega de còpia i es faciliten plantilles o fitxes.', 379),
  ('TEL/TDL', 'Universal', 'Es redueix la càrrega de còpia i es faciliten plantilles o fitxes.', 380),
  ('Altes capacitats', 'Addicional', 'Es reforça el vocabulari acadèmic amb pràctica espaiada i repetició.', 381),
  ('Dislèxia', 'Addicional', 'Es reforça el vocabulari acadèmic amb pràctica espaiada i repetició.', 382),
  ('NEE', 'Addicional', 'Es reforça el vocabulari acadèmic amb pràctica espaiada i repetició.', 383),
  ('Nouvingut', 'Addicional', 'Es reforça el vocabulari acadèmic amb pràctica espaiada i repetició.', 384),
  ('TDAH', 'Addicional', 'Es reforça el vocabulari acadèmic amb pràctica espaiada i repetició.', 385),
  ('TEA', 'Addicional', 'Es reforça el vocabulari acadèmic amb pràctica espaiada i repetició.', 386),
  ('TEL/TDL', 'Addicional', 'Es reforça el vocabulari acadèmic amb pràctica espaiada i repetició.', 387),
  ('Altes capacitats', 'Universal', 'Es reforcen rutines i senyals de transició per anticipar canvis.', 388),
  ('Dislèxia', 'Universal', 'Es reforcen rutines i senyals de transició per anticipar canvis.', 389),
  ('NEE', 'Universal', 'Es reforcen rutines i senyals de transició per anticipar canvis.', 390),
  ('Nouvingut', 'Universal', 'Es reforcen rutines i senyals de transició per anticipar canvis.', 391),
  ('TDAH', 'Universal', 'Es reforcen rutines i senyals de transició per anticipar canvis.', 392),
  ('TEA', 'Universal', 'Es reforcen rutines i senyals de transició per anticipar canvis.', 393),
  ('TEL/TDL', 'Universal', 'Es reforcen rutines i senyals de transició per anticipar canvis.', 394),
  ('Altes capacitats', 'Universal', 'Es registra el progrés amb una rúbrica simple o llista de verificació.', 395),
  ('Dislèxia', 'Universal', 'Es registra el progrés amb una rúbrica simple o llista de verificació.', 396),
  ('NEE', 'Universal', 'Es registra el progrés amb una rúbrica simple o llista de verificació.', 397),
  ('Nouvingut', 'Universal', 'Es registra el progrés amb una rúbrica simple o llista de verificació.', 398),
  ('TDAH', 'Universal', 'Es registra el progrés amb una rúbrica simple o llista de verificació.', 399),
  ('TEA', 'Universal', 'Es registra el progrés amb una rúbrica simple o llista de verificació.', 400),
  ('TEL/TDL', 'Universal', 'Es registra el progrés amb una rúbrica simple o llista de verificació.', 401),
  ('Altes capacitats', 'Intensiu', 'Es revisa el PI cada període amb evidències i ajustos acordats.', 402),
  ('Dislèxia', 'Intensiu', 'Es revisa el PI cada període amb evidències i ajustos acordats.', 403),
  ('NEE', 'Intensiu', 'Es revisa el PI cada període amb evidències i ajustos acordats.', 404),
  ('Nouvingut', 'Intensiu', 'Es revisa el PI cada període amb evidències i ajustos acordats.', 405),
  ('TDAH', 'Intensiu', 'Es revisa el PI cada període amb evidències i ajustos acordats.', 406),
  ('TEA', 'Intensiu', 'Es revisa el PI cada període amb evidències i ajustos acordats.', 407),
  ('TEL/TDL', 'Intensiu', 'Es revisa el PI cada període amb evidències i ajustos acordats.', 408),
  ('Altes capacitats', 'Universal', 'Es revisen i ajusten materials per evitar sobrecàrrega de text.', 409),
  ('Dislèxia', 'Universal', 'Es revisen i ajusten materials per evitar sobrecàrrega de text.', 410),
  ('NEE', 'Universal', 'Es revisen i ajusten materials per evitar sobrecàrrega de text.', 411),
  ('Nouvingut', 'Universal', 'Es revisen i ajusten materials per evitar sobrecàrrega de text.', 412),
  ('TDAH', 'Universal', 'Es revisen i ajusten materials per evitar sobrecàrrega de text.', 413),
  ('TEA', 'Universal', 'Es revisen i ajusten materials per evitar sobrecàrrega de text.', 414),
  ('TEL/TDL', 'Universal', 'Es revisen i ajusten materials per evitar sobrecàrrega de text.', 415),
  ('TEL/TDL', 'Addicional', 'Es treballa el vocabulari específic amb imatges, definicions simples i repetició.', 416),
  ('TEA', 'Addicional', 'Es treballen habilitats socials amb guions i pràctica en situacions reals.', 417)
ON CONFLICT (model, tipus, mesura) DO NOTHING;
