-- Seed data for pi_config_sabers_dig
-- Generated from Google Sheets _SABERS_DIG
-- Total rows: 85

INSERT INTO pi_config_sabers_dig (stage, group_name, full_text, short_text, sort_order)
VALUES
  ('ESO', NULL, 'Actualització del sistema operatiu i les aplicacions.', 'Actualització del sistema operatiu i les aplicacions.', 1),
  ('ESO', NULL, 'Adopció d''estratègies d''autoregulació en l''ús dels dispositius digitals.', 'Adopció d''estratègies d''autoregulació en l''ús dels dispositius digitals.', 2),
  ('ESO', NULL, 'Adopció d''estratègies eficients en la protecció del medi ambient.', 'Adopció d''estratègies eficients en la protecció del medi ambient.', 3),
  ('ESO', NULL, 'Adopció d''estratègies per la gestió del temps i l''autoregulació en l''ús de les tecnologies digitals.', 'Adopció d''estratègies per la gestió del temps i l''autoregulació en l''ús de les tecnologies digitals.', 4),
  ('ESO', NULL, 'Adopció de normes de comportament en els entorns digitals (netiqueta)', 'Adopció de normes de comportament en els entorns digitals.', 5),
  ('ESO', NULL, 'Aplicacions que permeten organitzar i categoritzar enllaços web.', 'Aplicacions que permeten organitzar i categoritzar enllaços web.', 6),
  ('ESO', NULL, 'Aplicació d''estratègies d''autoregulació en l''ús dels dispositius digitals (temps d''ús, moments de desconnexió...).', 'Aplicació d''estratègies d''autoregulació en l''ús dels dispositius digitals .', 7),
  ('ESO', NULL, 'Aplicació de criteris d''adequació per la selecció d''eines col·laboratives de producció digital (processador de textos, aplicacions de presentacions, blogs, aplicacions de creació web...) en funció de la tasca a realitzar.', 'Aplicació de criteris d''adequació per la selecció d''eines col·laboratives de producció digital en funció de la.', 8),
  ('ESO', NULL, 'Aplicació de criteris d''adequació per la selecció d''eines col·laboratives de producció digital en funció de la tasca a realitzar.', 'Aplicació de criteris d''adequació per la selecció d''eines col·laboratives de producció digital en funció de la.', 9),
  ('ESO', NULL, 'Aplicació de criteris d''adequació per la selecció dels canals de comunicació en digital (correu electrònic, entorn virtual d''aprenentatge, fòrums, murs virtuals, xats, web, blogs...) en funció de la tasca a realitzar.', 'Aplicació de criteris d''adequació per la selecció dels canals de comunicació en digital en funció de.', 10),
  ('ESO', NULL, 'Aplicació de criteris de benestar digital en l''expressió de la identitat digital, la personalitat i el coneixement en entorns digitals.', 'Aplicació de criteris de benestar digital en l''expressió de la identitat digital, la personalitat i el.', 11),
  ('ESO', NULL, 'Aplicació de criteris de desenvolupament social, d''impacte mediambiental i d''obsolescència programada, en la valoració crítica de la tecnologia.', 'Aplicació de criteris de desenvolupament social.', 12),
  ('ESO', NULL, 'Aplicació de criteris de publicació de produccions digitals en xarxes restringides (visibilitat de la publicació, autoria de la creació, propietat intel·lectual, repercussió de la publicació...).', 'Aplicació de criteris de publicació de produccions digitals en xarxes restringides .', 13),
  ('ESO', NULL, 'Aplicació de funcions de format avançades (canvi de mida del document, capçalera i peu, esquema, títols i sagnats).', 'Aplicació de funcions de format avançades .', 14),
  ('ESO', NULL, 'Aplicació de funcions de format avançades (columnes, interlineat, tabulacions, seccions de document...).', 'Aplicació de funcions de format avançades .', 15),
  ('ESO', NULL, 'Aplicació de les normes de comportament cívic en interaccions aprofitant les característiques tècniques dels entorns digitals de comunicació.', 'Aplicació de les normes de comportament cívic en interaccions aprofitant les característiques tècniques dels entorns digitals.', 16),
  ('ESO', NULL, 'Aplicació de mesures de protecció i definició de la identitat digital pròpia i la dels altres (informació sobre un mateix i els altres, dades personals, imatges personals i d''altri, comentaris, contactes, amistats, privacitat, seguretat dels comptes, empremta digital...).', 'Aplicació de mesures de protecció i definició de la identitat digital pròpia i la dels altres.', 17),
  ('ESO', NULL, 'Aplicació de tècniques de correcció postural', 'Aplicació de tècniques de correcció postural.', 18),
  ('ESO', NULL, 'Aplicació d''estratègies pròpies del pensament computacional (descomposició, identificació de patrons, abstracció i elaboració d''algoritmes).', 'Aplicació d''estratègies pròpies del pensament computacional .', 19),
  ('ESO', NULL, 'Assignació de permisos d''edició en produccions col·laboratives en l''ús d''aplicacions que no s''han utilitzat anteriorment.', 'Assignació de permisos d''edició en produccions col·laboratives en l''ús d''aplicacions que no s''han utilitzat anteriorment.', 20),
  ('ESO', NULL, 'Autorització i revocació de galetes (cookies) en la navegació per Internet.', 'Autorització i revocació de galetes  en la navegació per Internet.', 21),
  ('ESO', NULL, 'Citació de les fonts consultades (referències bibliogràfiques).', 'Citació de les fonts consultades .', 22),
  ('ESO', NULL, 'Coneixement de les característiques bàsiques dels diferents formats d''imatges (JPG, JPEG, PNG, GIF, SVG...).', 'Coneixement de les característiques bàsiques dels diferents formats d''imatges .', 23),
  ('ESO', NULL, 'Coneixement de les característiques bàsiques dels diferents formats d''àudio (MP3,WAV).', 'Coneixement de les característiques bàsiques dels diferents formats d''àudio .', 24),
  ('ESO', NULL, 'Coneixement de les característiques principals dels drets d''autoria.', 'Coneixement de les característiques principals dels drets d''autoria.', 25),
  ('ESO', NULL, 'Coneixement de webs adreçades a la verificació d''informació de referència (fact-cheking).', 'Coneixement de webs adreçades a la verificació d''informació de referència .', 26),
  ('ESO', NULL, 'Coneixement dels diferents tipus de llicència en les condicions d''ús de les produccions.', 'Coneixement dels diferents tipus de llicència en les condicions d''ús de les produccions.', 27),
  ('ESO', NULL, 'Coneixement dels drets d''autor i les llicències de les dades obtingudes.', 'Coneixement dels drets d''autor i les llicències de les dades obtingudes.', 28),
  ('ESO', NULL, 'Coneixement dels perills que comporta la desinformació, la informació errònia, i la informació maliciosa i el desordre informatiu.', 'Coneixement dels perills que comporta la desinformació, la informació errònia, i la informació maliciosa i el.', 29),
  ('ESO', NULL, 'Coneixement i detecció dels elements que denoten possibles entorns no segurs (pàgines web segures: https, cadenat i excés de publicitat.).', 'Coneixement i detecció dels elements que denoten possibles entorns no segurs .', 30),
  ('ESO', NULL, 'Coneixement i ús d''eines digitals per desar i organitzar la informació.', 'Coneixement i ús d''eines digitals per desar i organitzar la informació.', 31),
  ('ESO', NULL, 'Coneixement i ús d''extensions i complements (correctors ortogràfics, capturadors i gravadors de pantalla, accessibilitat, seguretat, etc.).', 'Coneixement i ús d''extensions i complements .', 32),
  ('ESO', NULL, 'Configuració de wifis segures a través de simuladors.', 'Configuració de wifis segures.', 33),
  ('ESO', NULL, 'Consulta i restauració de versions de l''historial de canvis del document', 'Consulta i restauració de versions de l''historial de canvis del document.', 34),
  ('ESO', NULL, 'Conversió de documents a diferents formats (PDF, .docx, .odt...).', 'Conversió de documents a diferents formats .', 35),
  ('ESO', NULL, 'Criteri responsable i sentit crític sobre la informació de notícies.', 'Criteri responsable i sentit crític sobre la informació de notícies.', 36),
  ('ESO', NULL, 'Disseny d''interfícies d''usuari amb criteris d''accessibilitat i responsius en el disseny de les aplicacions.', 'Disseny d''interfícies d''usuari amb criteris d''accessibilitat i responsius en el disseny de les aplicacions.', 37),
  ('ESO', NULL, 'Exportació i publicació de vídeo i d''àudio.', 'Exportació i publicació de vídeo i d''àudio.', 38),
  ('ESO', NULL, 'Gestió de l''historial de cerques per internet.', 'Gestió de l''historial de cerques per internet.', 39),
  ('ESO', NULL, 'Identificació de ciberdelictes (ciberbullying, smishing -pesca per SMS-, sèxting...).', 'Identificació de ciberdelictes .', 40),
  ('ESO', NULL, 'Identificació de l''aportació de les tecnologies al benestar.', 'Identificació de l''aportació de les tecnologies al benestar.', 41),
  ('ESO', NULL, 'Identificació de missatges de correu electrònic sospitosos que intenten obtenir informació sensible o que poden contenir programes maliciosos (pesca de credencials, virus...).', 'Identificació de missatges de correu electrònic sospitosos que intenten obtenir informació sensible o que poden contenir.', 42),
  ('ESO', NULL, 'Identificació de recursos d''ajuda en cas d''addicció.', 'Identificació de recursos d''ajuda en cas d''addicció.', 43),
  ('ESO', NULL, 'Identificació de riscos i amenaces en la navegació de llocs web (https, descàrregues malicioses...).', 'Identificació de riscos i amenaces en la navegació de llocs web .', 44),
  ('ESO', NULL, 'Identificació dels diferents aspectes subjectius que constitueixen la identitat digital  i la fan evolucionar (intenció pròpia, percepció dels altres, interaccions...).', 'Identificació dels diferents aspectes subjectius que constitueixen la identitat digital i la fan evolucionar .', 45),
  ('ESO', NULL, 'Identificació dels drets en el tractament de dades personals (accés, rectificació, supressió i oposició) i les polítiques de privacitat.', 'Identificació dels drets en el tractament de dades personals  i les polítiques de privacitat.', 46),
  ('ESO', NULL, 'Identificació dels elements que construeixen perfils automàtics comercials (historial de navegació, reaccions a les publicacions, seguiment d''enllaços...).', 'Identificació dels elements que construeixen perfils automàtics comercials .', 47),
  ('ESO', NULL, 'Identificació i prevenció de conductes addictives.', 'Identificació i prevenció de conductes addictives.', 48),
  ('ESO', NULL, 'Identificació i resolució de problemes tècnics comuns derivats de la manipulació de dispositius i ús d''entorns digitals (problemes de connectivitat, accés a plataformes amb contrasenya, problemes en la navegació, accessibilitat, configuració bàsica del sistema, etc.).', 'Identificació i resolució de problemes tècnics comuns derivats de la manipulació de dispositius i ús d''entorns.', 49),
  ('ESO', NULL, 'Inserció automàtica de taules de contingut.', 'Inserció automàtica de taules de contingut.', 50),
  ('ESO', NULL, 'Inserció d''elements avançats d''edició de vídeo (càirons, subtítols...).', 'Inserció d''elements avançats d''edició de vídeo .', 51),
  ('ESO', NULL, 'Inserció d''equacions en documents de text.', 'Inserció d''equacions en documents de text.', 52),
  ('ESO', NULL, 'Inserció de fórmules senzilles en fulls de càlcul. (sumar, comptar, comptar si, mitjana...)', 'Inserció de fórmules senzilles en fulls de càlcul.', 53),
  ('ESO', NULL, 'Instal·lació de programes i serveis de protecció dels dispositius (antivirus, antimalware, tallafocs).', 'Instal·lació de programes i serveis de protecció dels dispositius .', 54),
  ('ESO', NULL, 'Interpretació i elaboració de diagrames de flux per plantejar la programació d''una aplicació o d''una part de l''aplicació.', 'Interpretació i elaboració de diagrames de flux per plantejar la programació d''una aplicació o d''una part.', 55),
  ('ESO', NULL, 'Introducció dels conceptes relacionats amb la desinformació: la desinformació pròpiament dita (fake new), la informació errònia (difusió de notícies falses) i la mala informació (informació maliciosa).', 'Introducció dels conceptes relacionats amb la desinformació: la desinformació pròpiament dita.', 56),
  ('ESO', NULL, 'Organització de la informació en carpetes en local i en el núvol.', 'Organització de la informació en carpetes en local i en el núvol.', 57),
  ('ESO', NULL, 'Promoció i aplicació d''accions per a la reducció de l''impacte ambiental de la solució tecnològica.', 'Promoció i aplicació d''accions per a la reducció de l''impacte ambiental de la solució tecnològica.', 58),
  ('ESO', NULL, 'Protecció de les dades sensibles i biomètriques en entorns virtuals i a Internet.', 'Protecció de les dades sensibles i biomètriques en entorns virtuals i a Internet.', 59),
  ('ESO', NULL, 'Realització de còpies de seguretat.', 'Realització de còpies de seguretat.', 60),
  ('ESO', NULL, 'Reconeixement dels riscos associats a la recollida de dades personals a través de les cookies a Internet.', 'Reconeixement dels riscos associats a la recollida de dades personals.', 61),
  ('ESO', NULL, 'Reconeixement i detecció de la desinformació.', 'Reconeixement i detecció de la desinformació.', 62),
  ('ESO', NULL, 'Simplificació d''algoritmes mitjançant el disseny de funcions i/o procediments.', 'Simplificació d''algoritmes.', 63),
  ('ESO', NULL, 'Utilització d''imatges de llicència lliure.', 'Utilització d''imatges de llicència lliure.', 64),
  ('ESO', NULL, 'Utilització de funcions avançades d''edició d''imatge (canvi de resolució i mida dels arxius, selecció automàtica d''objectes...)', 'Utilització de funcions avançades d''edició d''imatge.', 65),
  ('ESO', NULL, 'Utilització de funcions avançades d''edició d''imatge (eliminació d''imperfeccions, ajustos de color: saturació, contrast i brillantor, eliminació de fons).', 'Utilització de funcions avançades d''edició d''imatge .', 66),
  ('ESO', NULL, 'Utilització de funcions avançades d''edició de l''àudio (silenci, canvis velocitat, canvis de volum, equalització).', 'Utilització de funcions avançades d''edició de l''àudio .', 67),
  ('ESO', NULL, 'Utilització de funcions avançades d''edició de vídeo (velocitat, efectes, croma, dividir pantalla i filtres).', 'Utilització de funcions avançades d''edició de vídeo .', 68),
  ('ESO', NULL, 'Utilització de funcions d''edició d''àudio (fosa d''obertura i fosa de tancament, efectes, utilització de pistes d''àudio, panorama de la pista...).', 'Utilització de funcions d''edició d''àudio .', 69),
  ('ESO', NULL, 'Utilització de grups de correu electrònic.', 'Utilització de grups de correu electrònic.', 70),
  ('ESO', NULL, 'Utilització de l''autenticació de dos factors (sempre que estigui disponible).', 'Utilització de l''autenticació de dos factors .', 71),
  ('ESO', NULL, 'Utilització de la navegació web en mode incògnit quan la cerca ho requereixi en base als criteris de protecció de dades.', 'Utilització de la navegació web en mode incògnit quan la cerca ho requereixi en base als.', 72),
  ('ESO', NULL, 'Utilització de les estructures de programació comunes a la majoria de llenguatges (constants, variables, operadors, condicionals, repeticions i esdeveniments) en llenguatges per blocs i en llenguatges textuals.', 'Utilització de les estructures de programació comunes a la majoria de llenguatges en llenguatges per blocs.', 73),
  ('ESO', NULL, 'Utilització de les funcionalitats de seguiment de la col·laboració en digital en l''ús d''aplicacions que no s''han utilitzat anteriorment.', 'Utilització de les funcionalitats de seguiment de la col·laboració en digital en l''ús d''aplicacions que no.', 74),
  ('ESO', NULL, 'Utilització de les funcions dels fulls de càlcul per generar gràfics senzills (diagrames de barres, diagrames de sectors...)', 'Utilització de les funcions dels fulls de càlcul per generar gràfics senzills.', 75),
  ('ESO', NULL, 'Utilització de plaques d''extensió per a plaques programables en les solucions tecnològiques proposades.', 'Utilització de plaques d''extensió per a plaques programables en les solucions tecnològiques proposades.', 76),
  ('ESO', NULL, 'Utilització dels sensors integrats i externs de plaques programables educatives.', 'Utilització dels sensors integrats i externs de plaques programables educatives.', 77),
  ('ESO', NULL, 'Valoració de les implicacions de compartir opinions, informacions i/o material audiovisual propies o de tercers (amb o sense consentiment).', 'Valoració de les implicacions de compartir opinions, informacions i/o material audiovisual propies o de tercers .', 78),
  ('ESO', NULL, 'Ús d''estratègies de cerca avançada (ús d''opcions de cerca contextual dels navegadors i operadors lògics: ús de cometes, -and, not/-, or-...).', 'Ús d''estratègies de cerca avançada .', 79),
  ('ESO', NULL, 'Ús d''indicacions eficients en els xatbots per a la cerca d''informació.', 'Ús d''indicacions eficients en els xatbots per a la cerca d''informació.', 80),
  ('ESO', NULL, 'Ús de criteris de verificació en la cerca d''informació (contrast de la informació, verificació de la font en aquells xatbots en què ho indiqui).', 'Ús de criteris de verificació en la cerca d''informació .', 81),
  ('ESO', NULL, 'Ús de criteris de verificació en la cerca d''informació.', 'Ús de criteris de verificació en la cerca d''informació.', 82),
  ('ESO', NULL, 'Ús de dreceres de teclat avançades per seleccionar tot el text, enganxar sense format, negreta (dreceres subjectes a programari).', 'Ús de dreceres de teclat avançades per seleccionar tot el text, enganxar sense format, negreta .', 83),
  ('ESO', NULL, 'Ús de la connectivitat wifi de robots educatius i plaques programables en les solucions tecnològiques proposades.', 'Ús de la connectivitat wifi de robots educatius i plaques programables en les solucions tecnològiques proposades.', 84),
  ('ESO', NULL, 'Ús de llicències de programari de forma legal i respectuosa. 
Identificació i valoració dels principis de la propietat intel·lectual i drets d''autor.', 'Ús de llicències de programari de forma legal i respectuosa. Identificació i valoració dels principis de.', 85)
ON CONFLICT DO NOTHING;
